global:
 external_labels:
  site: project

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: node-exporter
    scrape_interval: 5s
#    scheme: https
#    basic_auth:
#      username: prometheus
#      password: 12345
#    tls_config:
#      ca_file: /opt/prometheus/my_site.crt
#      insecure_skip_verify: true
#    metrics_path: /monitoring/node_exporter
    static_configs:
    - targets:
      - ceph-srv1:9100
      - ceph-srv2:9100
      - ceph-srv3:9100
      - db-srv1:9100
      - db-srv2:9100
      - db-srv3:9100
      - web-srv1:9100
      - web-srv2:9100
      - lb-srv1:9100
      - lb-srv2:9100
      - mon-srv1:9100
      - mon-srv2:9100

  - job_name: ceph-exporter
    scrape_interval: 5s
    static_configs:
    - targets:
      - ceph-srv1:9283
      - ceph-srv2:9283
      - ceph-srv3:9283

  - job_name: haproxy-exporter
    scrape_interval: 5s
    static_configs:
    - targets:
      - lb-srv:8404

#  - job_name: mysql-exporter
#    scheme: https
#    basic_auth:
#      username: prometheus
#      password: 12345
#    tls_config:
#      ca_file: /opt/prometheus/my_site.crt
#      insecure_skip_verify: true
#    metrics_path: /monitoring/mysql_exporter
#    static_configs:
#    - targets:
#      - db-srv1:9104
#      - db-srv2:9104
#      - db-srv3:9104


#  - job_name: nginx-exporter-tls
#    scheme: https
#    basic_auth:
#      username: prometheus
#      password: 12345
#    tls_config:
#      ca_file: /opt/prometheus/my_site.crt
#      insecure_skip_verify: true
#    metrics_path: /monitoring/nginx_exporter
#    static_configs:
#    - targets:
#      - my_site.local:443

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
    - targets:
      - https://my_site.local
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9115

remote_write:
  - url: http://127.0.0.1:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['127.0.0.1:9093']

rule_files:
  - "alert.rules.yml"
