global:
 scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: node-exporter-tls
    scheme: https
    basic_auth:
      username: prometheus
      password: 12345
    tls_config:
      ca_file: /opt/prometheus/my_site.crt
      insecure_skip_verify: true
    metrics_path: /monitoring/node_exporter
    static_configs:
    - targets:
      - my_site.local:443

  - job_name: mysql-exporter-tls
    scheme: https
    basic_auth:
      username: prometheus
      password: 12345
    tls_config:
      ca_file: /opt/prometheus/my_site.crt
      insecure_skip_verify: true
    metrics_path: /monitoring/mysql_exporter
    static_configs:
    - targets:
      - my_site.local:443

  - job_name: nginx-exporter-tls
    scheme: https
    basic_auth:
      username: prometheus
      password: 12345
    tls_config:
      ca_file: /opt/prometheus/my_site.crt
      insecure_skip_verify: true
    metrics_path: /monitoring/nginx_exporter
    static_configs:
    - targets:
      - my_site.local:443

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
    - targets:
      - https://my_site.local
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9115